spring:
  datasource:
    url: jdbc:postgresql://${database.url:localhost}:${database.port:5432}/jpa_demo
    driver-class-name: org.postgresql.Driver
    username: ${database.username:root}
    password: ${database.password:letmein}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB